import { Link, NavLink, Route, Routes, useNavigate, useSearchParams } from "react-router-dom";
import { Heart, Search, ShoppingCart, UserRound, Star, Plus, Minus, Trash2, ArrowRight, Package } from "lucide-react";
import { products,categories } from "./data";
import { Product } from "./types";
import { useShop } from "./store/ShopContext";
import { useState } from "react";

function Header(){
 const nav=useNavigate(); const {cartCount,favorites}=useShop(); const [q,setQ]=useState("");
 return <header><div className="top"><Link to="/" className="brand"><b>F</b><span>Fssyoush</span></Link>
 <form className="search" onSubmit={e=>{e.preventDefault();nav("/catalog?search="+encodeURIComponent(q))}}><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Искать товары..."/><button>Найти</button></form>
 <nav><Link to="/account"><UserRound/> <span>Войти</span></Link><Link to="/favorites"><Heart/><i>{favorites.length}</i></Link><Link to="/cart"><ShoppingCart/><i>{cartCount}</i></Link></nav></div>
 <div className="cats">{categories.map(c=><Link key={c} to={"/catalog?category="+encodeURIComponent(c)}>{c}</Link>)}</div></header>
}
function Footer(){return <footer><div className="footer-in"><div><div className="brand"><b>F</b><span>Fssyoush</span></div><p>Современный маркетплейс для удобных покупок.</p></div><div><strong>Покупателям</strong><Link to="/catalog">Каталог</Link><Link to="/favorites">Избранное</Link><Link to="/cart">Корзина</Link></div><div><strong>Помощь</strong><a href="#delivery">Доставка</a><a href="#support">Поддержка</a></div></div><small>© 2026 Fssyoush</small></footer>}
function Card({p}:{p:Product}){const {addToCart,toggleFavorite,favorites}=useShop();const fav=favorites.includes(p.id);return <article className="card"><Link to={"/product/"+p.id} className="pic"><img loading="lazy" src={p.image}/>{p.oldPrice&&<em>-{Math.round((1-p.price/p.oldPrice)*100)}%</em>}<button className={fav?"fav active":"fav"} onClick={e=>{e.preventDefault();toggleFavorite(p.id)}}><Heart fill={fav?"currentColor":"none"}/></button></Link><div className="cardbody"><div className="rating"><Star size={15} fill="currentColor"/>{p.rating} <span>({p.reviews})</span></div><Link to={"/product/"+p.id} className="pname">{p.name}</Link><div className="price">{p.price.toFixed(2)} <small>€</small>{p.oldPrice&&<del>{p.oldPrice.toFixed(2)} €</del>}</div><button className="add" onClick={()=>addToCart(p)}>В корзину</button></div></article>}
function Home(){return <main><section className="hero"><div><span>НОВАЯ КОЛЛЕКЦИЯ</span><h1>Покупки, которые<br/><b>радуют каждый день</b></h1><p>Товары для дома, электроника, одежда и многое другое.</p><Link className="hero-btn" to="/catalog">Перейти в каталог <ArrowRight/></Link></div><div className="hero-art">F</div></section><section><h2>Популярные категории</h2><div className="category-grid">{categories.slice(0,8).map((c,i)=><Link to={"/catalog?category="+encodeURIComponent(c)} key={c}><span>{["⚡","👟","👕","✨","🏠","🎒","📱","📷"][i]}</span><b>{c}</b></Link>)}</div></section><section><div className="section-head"><h2>Популярные товары</h2><Link to="/catalog">Смотреть все</Link></div><div className="grid">{products.slice(0,10).map(p=><Card key={p.id} p={p}/>)}</div></section><section><div className="orange-banner"><div><span>FSSYOUSH SALE</span><h2>Скидки до 40%</h2><p>Успейте выбрать любимые товары.</p><Link to="/catalog">Смотреть скидки</Link></div></div></section><section><div className="section-head"><h2>Новинки</h2><Link to="/catalog">Все новинки</Link></div><div className="grid">{products.slice(10,15).map(p=><Card key={p.id} p={p}/>)}</div></section></main>}
function Catalog(){const [params]=useSearchParams();const [sort,setSort]=useState("popular");const search=(params.get("search")||"").toLowerCase();const cat=params.get("category")||"";let list=products.filter(p=>(!cat||p.category===cat)&&(!search||[p.name,p.category,...p.keywords].join(" ").toLowerCase().includes(search)));if(sort==="priceUp")list.sort((a,b)=>a.price-b.price);if(sort==="priceDown")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);return <main className="container page"><div className="catalog-head"><div><h1>{cat||"Каталог"}</h1><p>{search?`По запросу «${search}» найдено ${list.length}`:`${list.length} товаров`}</p></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">По популярности</option><option value="rating">По рейтингу</option><option value="priceUp">Сначала дешевле</option><option value="priceDown">Сначала дороже</option></select></div><div className="catalog-layout"><aside><b>Категории</b>{categories.map(c=><Link className={cat===c?"selected":""} key={c} to={"/catalog?category="+encodeURIComponent(c)}>{c}</Link>)}<Link to="/catalog">Все товары</Link></aside><div className="grid">{list.map(p=><Card key={p.id} p={p}/>)}</div></div></main>}
function ProductPage({id}:{id:string}){const p=products.find(x=>x.id===Number(id));const {addToCart,toggleFavorite,favorites}=useShop();const [qty,setQty]=useState(1);if(!p)return <div className="container page"><h1>Товар не найден</h1></div>;return <main className="container page"><div className="product"><div className="product-image"><img src={p.image}/>{p.oldPrice&&<em>-{Math.round((1-p.price/p.oldPrice)*100)}%</em>}</div><div><div className="rating"><Star size={17} fill="currentColor"/>{p.rating} · {p.reviews} отзывов</div><h1>{p.name}</h1><p className="desc">{p.description}</p><div className="bigprice">{p.price.toFixed(2)} € {p.oldPrice&&<del>{p.oldPrice.toFixed(2)} €</del>}</div><p>В наличии: <b>{p.stock} шт.</b></p><div className="options"><b>Цвет:</b>{p.colors.map(c=><button key={c}>{c}</button>)}</div><div className="options"><b>Размер:</b>{p.sizes.map(s=><button key={s}>{s}</button>)}</div><div className="buyrow"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button>{qty}<button onClick={()=>setQty(qty+1)}><Plus/></button></div><button className="add mainadd" onClick={()=>{for(let i=0;i<qty;i++)addToCart(p)}}>Добавить в корзину</button><button className={favorites.includes(p.id)?"iconbtn active":"iconbtn"} onClick={()=>toggleFavorite(p.id)}><Heart fill={favorites.includes(p.id)?"currentColor":"none"}/></button></div><div className="delivery"><Package/> Доставка по городу от 1–3 дней</div></div></div><section><h2>Похожие товары</h2><div className="grid">{products.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,5).map(x=><Card key={x.id} p={x}/>)}</div></section></main>}
function Cart(){const {cart,cartTotal,setQty,removeFromCart}=useShop();if(!cart.length)return <main className="container page"><div className="empty"><ShoppingCart size={48}/><h1>Корзина пуста</h1><p>Добавьте товары из каталога.</p><Link className="hero-btn" to="/catalog">Перейти в каталог</Link></div></main>;return <main className="container page"><h1>Корзина</h1><div className="cart-layout"><div>{cart.map(i=><div className="cartitem" key={i.product.id}><img src={i.product.image}/><div><Link to={"/product/"+i.product.id}><b>{i.product.name}</b></Link><p>{i.product.price.toFixed(2)} €</p><div className="qty"><button onClick={()=>setQty(i.product.id,i.quantity-1)}><Minus/></button>{i.quantity}<button onClick={()=>setQty(i.product.id,i.quantity+1)}><Plus/></button></div></div><strong>{(i.product.price*i.quantity).toFixed(2)} €</strong><button className="delete" onClick={()=>removeFromCart(i.product.id)}><Trash2/></button></div>)}</div><aside className="summary"><h2>Итого</h2><p>Товары <b>{cartTotal.toFixed(2)} €</b></p><p>Доставка <b>Бесплатно</b></p><hr/><h2>{cartTotal.toFixed(2)} €</h2><Link className="add checkout" to="/checkout">Оформить заказ</Link></aside></div></main>}
function Account(){const [logged,setLogged]=useState(!!localStorage.getItem("fssyoush-user"));return <main className="container page"><div className="account">{logged?<><h1>Личный кабинет</h1><p>Добро пожаловать в Fssyoush.</p><button className="add" onClick={()=>{localStorage.removeItem("fssyoush-user");setLogged(false)}}>Выйти</button></>:<><h1>Вход</h1><p>Демо-авторизация для локального магазина.</p><button className="add" onClick={()=>{localStorage.setItem("fssyoush-user","demo");setLogged(true)}}>Войти как покупатель</button></>}</div></main>}
function Checkout(){const {cart,cartTotal}=useShop();const [done,setDone]=useState(false);if(done)return <main className="container page"><div className="empty"><Package size={48}/><h1>Заказ успешно оформлен!</h1><p>Номер заказа: <b>FS-{Date.now().toString().slice(-7)}</b></p><Link className="hero-btn" to="/">На главную</Link></div></main>;return <main className="container page"><h1>Оформление заказа</h1><div className="checkout-layout"><form className="checkout-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><input required placeholder="Имя"/><input required placeholder="Фамилия"/><input required placeholder="Телефон"/><input required placeholder="Город"/><input required placeholder="Адрес"/><select><option>Курьерская доставка</option><option>Пункт выдачи</option></select><select><option>Оплата при получении</option><option>Картой онлайн</option></select><button className="add" type="submit">Подтвердить заказ</button></form><aside className="summary"><h2>Ваш заказ</h2>{cart.map(i=><p key={i.product.id}>{i.product.name} × {i.quantity}</p>)}<hr/><h2>{cartTotal.toFixed(2)} €</h2></aside></div></main>}
function Favorites(){const {favorites}=useShop();const list=products.filter(p=>favorites.includes(p.id));return <main className="container page"><h1>Избранное</h1>{list.length?<div className="grid">{list.map(p=><Card key={p.id} p={p}/>)}</div>:<div className="empty"><Heart size={48}/><h2>Здесь пока пусто</h2><Link className="hero-btn" to="/catalog">Выбрать товары</Link></div>}</main>}
function App(){return <><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/catalog" element={<Catalog/>}/><Route path="/product/:id" element={<ProductRoute/>}/><Route path="/cart" element={<Cart/>}/><Route path="/favorites" element={<Favorites/>}/><Route path="/account" element={<Account/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="*" element={<Home/>}/></Routes><Footer/><div className="mobile-nav"><Link to="/">Главная</Link><Link to="/catalog">Каталог</Link><Link to="/favorites">Избранное</Link><Link to="/cart">Корзина</Link><Link to="/account">Профиль</Link></div></>}
function ProductRoute(){const {id}=requireParams();return <ProductPage id={id}/>}; function requireParams(){const path=location.pathname.split("/");return {id:path[2]||""}}
export default App;